trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
- group: AWS-Variables

- name: IMAGE_NAME
  value: devsecops-app
  
- name: IMAGE_TAG
  value: $(Build.BuildId)

stages:

- stage: CI
  displayName: "Continuous Integration"

  jobs:

  - job: BuildAndScan
    displayName: "Build, Scan and Publish"

    steps:

    - checkout: self

    - task: NodeTool@0
      displayName: Install Node.js

      inputs:
        versionSpec: '20.x'

    - script: |
        chmod +x scripts/*.sh
      displayName: Give Execute Permission

    - script: |
        ./scripts/build.sh
      displayName: Build Application

    - script: |
        ./scripts/install-trivy.sh
      displayName: Install Trivy

    - script: |
        ./scripts/scan-image.sh
      displayName: Scan Docker Image