trigger: 
  - main

pool: 
  vmImage: 'ubuntu-latest'

variables: 
  - group: 'AWS-Variables'

stages:
  - stage: Build
    displayName: "Checkout and Build"

    jobs: 

      - job: BuildJob
        displayName: "Checkout Repository"

        steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '20.x'
          displayName: 'Install Node.js'

        - script: |
            cd app
            npm install
          displayName: 'Install Node Dependencies'

        - script: |
            cd app
            timeout 10s npm start || true
          displayName: 'Verify Application Starts'

        - script: |
            cd app

            docker build \
              -t devsecops-app:$(Build.BuildId) \
              .
          displayName: 'Build Docker Image'

        - script: |
            docker images
          displayName: 'List Docker Images'

        - script: |
            sudo apt-get update
            sudo apt-get install -y wget

            wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.0_Linux-64bit.deb

            sudo dpkg -i trivy_0.65.0_Linux-64bit.deb
          displayName: 'Install Trivy'

        - script: |
            trivy --version
          displayName: 'Verify Trivy Installation'

        - script: |
            trivy image devsecops-app:$(Build.BuildId)
          displayName: 'Scan Docker Image'

      
          