trigger: 
  - main

pool: 
  vmImage: 'ubuntu-latest'

variables: 
  - group: 'AWS-Variables'

stages:
  - stage: Build
    displayName: "Checkout and Build"

    jobs: 

      - job: BuildJob
        displayName: "Checkout Repository"

        steps:
        - checkout: self

        - task: NodeTool@0
          inputs:
            versionSpec: '20.x'
          displayName: 'Install Node.js'

        - script: |
            cd app
            npm install
          displayName: 'Install Node Dependencies'

        - script: |
            cd app
            timeout 10s npm start || true
          displayName: 'Verify Application Starts'

        - script: |
            cd app

            docker build \
              -t devsecops-app:$(Build.BuildId) \
              .
          displayName: 'Build Docker Image'

        - script: |
            docker images
          displayName: 'List Docker Images'
          